export class Location {

    constructor(
        public locationID?: string,
        public higherGeographyID?: string,
        public higherGeography?: string,
        public continent?: string,
        public waterBody?: string,
        public islandGroup?: string,
        public island?: string,
        public country?: string,
        public countryCode?: string,
        public stateProvince?: string,
        public county?: string,
        public municipality?: string,
        public locality?: string,
        public verbatimLocality?: string,
        public minimumElevationInMeters?: string,
        public maximumElevationInMeters?: string,
        public verbatimElevation?: string,
        public minimumDepthInMeters?: string,
        public maximumDepthInMeters?: string,
        public verbatimDepth?: string,
        public minimumDistanceAboveSurfaceInMeters?: string,
        public maximumDistanceAboveSurfaceInMeters?: string,
        public locationAccordingTo?: string,
        public locationRemarks?: string,
        public decimalLatitude?: string,
        public decimalLongitude?: string,
        public geodeticDatum?: string,
        public coordinateUncertaintyInMeters?: string,
        public coordinatePrecision?: string,
        public pointRadiusSpatialFit?: string,
        public verbatimCoordinates?: string,
        public verbatimLatitude?: string,
        public verbatimLongitude?: string,
        public verbatimCoordinateSystem?: string,
        public verbatimSRS?: string,
        public footprintWKT?: string,
        public footprintSRS?: string,
        public footprintSpatialFit?: string,
        public georeferencedBy?: string,
        public georeferencedDate?: string,
        public georeferenceProtocol?: string,
        public georeferenceSources?: string,
        public georeferenceVerificationStatus?: string,
        public georeferenceRemarks?: string,
        public _id?: string
    ) { }

}