export class Taxon {

    constructor(
        public taxonID?:string,
        public scientificNameID?:string,
        public acceptedNameUsageID?:string,
        public parentNameUsageID?:string,
        public originalNameUsageID?:string,
        public nameAccordingToID?:string,
        public namePublishedInID?:string,
        public taxonConceptID?:string,
        public scientificName?:string,
        public acceptedNameUsage?:string,
        public parentNameUsage?:string,
        public originalNameUsage?:string,
        public nameAccordingTo?:string,
        public namePublishedIn?:string,
        public namePublishedInYear?:string,
        public higherClassification?:string,
        public kingdom?:string,
        public phylum?:string,
        public _class?:string,
        public order?:string,
        public family?:string,
        public genus?:string,
        public subgenus?:string,
        public specificEpithet?:string,
        public infraspecificEpithet?:string,
        public taxonRank?:string,
        public verbatimTaxonRank?:string,
        public scientificNameAuthorship?:string,
        public vernacularName?:string,
        public nomenclaturalCode?:string,
        public taxonomicStatus?:string,
        public nomenclaturalStatus?:string,
        public taxonRemarks?:string,
        public id?: string
    ) { }

}